### ISSUE TITLE
count only the existence of a certain path in a record for percentage statistics

### ISSUE THREAD

**Issue by boferri** [slub/jsonl-fstats#12]
otherwise, it looks like that these statistics are a bit skew. from my knowledge or guess, currently each occurrence of a certain path will be count, i.e., if a path has multiple values it will be count twice and so on. if one has paths with multiple values, this percentage statistics could end up with more than 100% (which will be cut right now (from my knowledge)). however, when only counting the existence of a certain path (instead of all occurrences) in a record, this count won't get larger than 100% (which is the number total records).

**Comment by boerni667** [comment]
https://github.com/slub/jsonl-fstats/commit/1d950fbd1c68a72d60e82739f1b8a0c39ec96cc3

**Comment by boferri** [comment]
I think, it works ;)
