### ISSUE TITLE
separate columns for "occurence" and "existing"

### ISSUE THREAD

**Issue by boferri** [slub/jsonl-fstats#13]
currently, the value of "existing" for a certain field, reflects all occurrences of this field over all records. however, to align the meaning of "existing" to the meaning of "not-existing", we should only count the existence of a certain path (instead of all occurrences) in a record for "existing". the current value of existing should be written into a separate column (e.g. "occurence").

**Comment by boerni667** [comment]
fixed with c0fe9eb
