### ISSUE TITLE
(re-)include non-leaf-fields in resulting statistic

### ISSUE THREAD

**Issue by boferri** [slub/jsonl-fstats#18]
currently, it looks like that only leaf-fields will be included into the resulting statistic. however, it would be nice to also get the statistics of non-leaf-fields.

**Comment by boerni667** [comment]
after several testing sessions, no fix for this issue could be found.

it collides with issue #6.

**Comment by boerni667** [comment]
try 74409e612adb1ad52a11dc41cf1e9cfe928cf83e
