### ISSUE TITLE
print field paths of nested fields

### ISSUE THREAD

**Issue by boferri** [slub/jsonl-fstats#5]
e.g.
```
metadata > base_dc:dc > xmlns:base_dc
```

**Comment by boerni667** [comment]
issue concerns the elasticsearch based fstats-tool, not the json-based tool. ;)

**Comment by boferri** [comment]
sorry, this was no issue. it is a feature request, hence still valid ;)

**Comment by boerni667** [comment]
fixed with commit b27972bd8690d681a454acc5a55030820386b6ae
